[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.6.1" }
remodel = { source = "rojo-rbx/remodel", version = "0.9.1" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.13.1" }
selene = { source = "Kampfkarren/selene", version = "0.17" }
lune = { source = "lune-org/lune", version = "0.10.4" }
